version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - 5000:5000
      - 5002:2345
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: test-web
    depends_on:
      - database

  database:
    image: postgres
    env_file: 
      .env
    container_name: test-db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 33066:3306
    volumes:
      - dsign_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 5001:8080

volumes:
  dsign_db:
      